/* C89 port: compatibility aliases for old dav1d enum names -> new C89 names */
/* Include this AFTER levels_c89.h to map old table code to new names */

#ifndef STB_AV1_LEVELS_COMPAT_H
#define STB_AV1_LEVELS_COMPAT_H

#include "dav1d_ref/levels_c89.h"

/* Block levels */
#define BL_128X128 STB_AV1_BL_128X128
#define BL_64X64   STB_AV1_BL_64X64
#define BL_32X32   STB_AV1_BL_32X32
#define BL_16X16   STB_AV1_BL_16X16
#define BL_8X8     STB_AV1_BL_8X8
#define N_BL_LEVELS STB_AV1_N_BL_LEVELS

/* Partitions */
#define PARTITION_NONE           STB_AV1_PARTITION_NONE
#define PARTITION_H              STB_AV1_PARTITION_H
#define PARTITION_V              STB_AV1_PARTITION_V
#define PARTITION_SPLIT          STB_AV1_PARTITION_SPLIT
#define PARTITION_T_TOP_SPLIT    STB_AV1_PARTITION_T_TOP_SPLIT
#define PARTITION_T_BOTTOM_SPLIT STB_AV1_PARTITION_T_BOTTOM_SPLIT
#define PARTITION_T_LEFT_SPLIT   STB_AV1_PARTITION_T_LEFT_SPLIT
#define PARTITION_T_RIGHT_SPLIT  STB_AV1_PARTITION_T_RIGHT_SPLIT
#define PARTITION_H4             STB_AV1_PARTITION_H4
#define PARTITION_V4             STB_AV1_PARTITION_V4
#define N_PARTITIONS             STB_AV1_N_PARTITIONS
#define N_SUB8X8_PARTITIONS      STB_AV1_N_SUB8X8_PARTITIONS

/* Block sizes */
#define BS_128x128 STB_AV1_BS_128x128
#define BS_128x64  STB_AV1_BS_128x64
#define BS_64x128  STB_AV1_BS_64x128
#define BS_64x64   STB_AV1_BS_64x64
#define BS_64x32   STB_AV1_BS_64x32
#define BS_64x16   STB_AV1_BS_64x16
#define BS_32x64   STB_AV1_BS_32x64
#define BS_32x32   STB_AV1_BS_32x32
#define BS_32x16   STB_AV1_BS_32x16
#define BS_32x8    STB_AV1_BS_32x8
#define BS_16x64   STB_AV1_BS_16x64
#define BS_16x32   STB_AV1_BS_16x32
#define BS_16x16   STB_AV1_BS_16x16
#define BS_16x8    STB_AV1_BS_16x8
#define BS_16x4    STB_AV1_BS_16x4
#define BS_8x32    STB_AV1_BS_8x32
#define BS_8x16    STB_AV1_BS_8x16
#define BS_8x8     STB_AV1_BS_8x8
#define BS_8x4     STB_AV1_BS_8x4
#define BS_4x16    STB_AV1_BS_4x16
#define BS_4x8     STB_AV1_BS_4x8
#define BS_4x4     STB_AV1_BS_4x4
#define N_BS_SIZES STB_AV1_N_BS_SIZES

/* Transform sizes */
#define TX_4X4     STB_AV1_TX_4X4
#define TX_8X8     STB_AV1_TX_8X8
#define TX_16X16   STB_AV1_TX_16X16
#define TX_32X32   STB_AV1_TX_32X32
#define TX_64X64   STB_AV1_TX_64X64
#define N_TX_SIZES STB_AV1_N_TX_SIZES

/* Rect transform sizes */
#define RTX_4X8  STB_AV1_RTX_4X8
#define RTX_8X4  STB_AV1_RTX_8X4
#define RTX_8X16  STB_AV1_RTX_8X16
#define RTX_16X8  STB_AV1_RTX_16X8
#define RTX_16X32 STB_AV1_RTX_16X32
#define RTX_32X16 STB_AV1_RTX_32X16
#define RTX_32X64 STB_AV1_RTX_32X64
#define RTX_64X32 STB_AV1_RTX_64X32
#define RTX_4X16  STB_AV1_RTX_4X16
#define RTX_16X4  STB_AV1_RTX_16X4
#define RTX_8X32  STB_AV1_RTX_8X32
#define RTX_32X8  STB_AV1_RTX_32X8
#define RTX_16X64 STB_AV1_RTX_16X64
#define RTX_64X16 STB_AV1_RTX_64X16
#define N_RECT_TX_SIZES STB_AV1_N_RECT_TX_SIZES

/* Transform types */
#define DCT_DCT STB_AV1_DCT_DCT
#define ADST_DCT STB_AV1_ADST_DCT
#define DCT_ADST STB_AV1_DCT_ADST
#define ADST_ADST STB_AV1_ADST_ADST
#define FLIPADST_DCT STB_AV1_FLIPADST_DCT
#define DCT_FLIPADST STB_AV1_DCT_FLIPADST
#define FLIPADST_FLIPADST STB_AV1_FLIPADST_FLIPADST
#define ADST_FLIPADST STB_AV1_ADST_FLIPADST
#define FLIPADST_ADST STB_AV1_FLIPADST_ADST
#define IDTX STB_AV1_IDTX
#define V_DCT STB_AV1_V_DCT
#define H_DCT STB_AV1_H_DCT
#define V_ADST STB_AV1_V_ADST
#define H_ADST STB_AV1_H_ADST
#define V_FLIPADST STB_AV1_V_FLIPADST
#define H_FLIPADST STB_AV1_H_FLIPADST
#define N_TX_TYPES STB_AV1_N_TX_TYPES
#define WHT_WHT STB_AV1_WHT_WHT
#define N_TX_TYPES_PLUS_LL STB_AV1_N_TX_TYPES_PLUS_LL

/* TX classes */
#define TX_CLASS_2D STB_AV1_TX_CLASS_2D
#define TX_CLASS_H  STB_AV1_TX_CLASS_H
#define TX_CLASS_V  STB_AV1_TX_CLASS_V

/* Intra prediction modes */
#define DC_PRED STB_AV1_DC_PRED
#define VERT_PRED STB_AV1_VERT_PRED
#define HOR_PRED STB_AV1_HOR_PRED
#define DIAG_DOWN_LEFT_PRED STB_AV1_DIAG_DOWN_LEFT_PRED
#define SMOOTH_PRED STB_AV1_SMOOTH_PRED
#define PAETH_PRED STB_AV1_PAETH_PRED
#define CFL_PRED STB_AV1_CFL_PRED
#define Z1_PRED STB_AV1_Z1_PRED
#define Z2_PRED STB_AV1_Z2_PRED
#define Z3_PRED STB_AV1_Z3_PRED
#define FILTER_PRED STB_AV1_FILTER_PRED
#define N_INTRA_PRED_MODES STB_AV1_N_INTRA_PRED_MODES
#define N_UV_INTRA_PRED_MODES STB_AV1_N_UV_INTRA_PRED_MODES

/* Inter modes */
#define NEARESTMV STB_AV1_NEARESTMV
#define NEARMV    STB_AV1_NEARMV
#define GLOBALMV  STB_AV1_GLOBALMV
#define NEWMV     STB_AV1_NEWMV
#define N_INTER_PRED_MODES STB_AV1_N_INTER_PRED_MODES

/* Compound prediction modes */
#define NEARESTMV_NEARESTMV STB_AV1_NEARESTMV_NEARESTMV
#define NEARMV_NEARMV       STB_AV1_NEARMV_NEARMV
#define NEARESTMV_NEWMV     STB_AV1_NEARESTMV_NEWMV
#define NEWMV_NEARESTMV     STB_AV1_NEWMV_NEARESTMV
#define NEARMV_NEWMV        STB_AV1_NEARMV_NEWMV
#define NEWMV_NEARMV        STB_AV1_NEWMV_NEARMV
#define GLOBALMV_GLOBALMV   STB_AV1_GLOBALMV_GLOBALMV
#define NEWMV_NEWMV         STB_AV1_NEWMV_NEWMV
#define N_COMP_INTER_PRED_MODES STB_AV1_N_COMP_INTER_PRED_MODES

/* Filter 2D */
#define FILTER_2D_8TAP_REGULAR STB_AV1_FILTER_2D_8TAP_REGULAR
#define FILTER_2D_BILINEAR STB_AV1_FILTER_2D_BILINEAR
#define N_2D_FILTERS STB_AV1_N_2D_FILTERS

/* MV joints */
#define MV_JOINT_ZERO STB_AV1_MV_JOINT_ZERO
#define MV_JOINT_H    STB_AV1_MV_JOINT_H
#define MV_JOINT_V    STB_AV1_MV_JOINT_V
#define N_MV_JOINTS   STB_AV1_N_MV_JOINTS

/* Inter-intra */
#define II_DC_PRED     STB_AV1_II_DC_PRED
#define II_VERT_PRED   STB_AV1_II_VERT_PRED
#define II_HOR_PRED    STB_AV1_II_HOR_PRED
#define II_SMOOTH_PRED STB_AV1_II_SMOOTH_PRED

/* Motion modes */
#define MM_TRANSLATION STB_AV1_MM_TRANSLATION
#define MM_OBMC        STB_AV1_MM_OBMC

/* DRL */
#define NEAREST_DRL STB_AV1_NEAREST_DRL
#define NEARER_DRL  STB_AV1_NEARER_DRL
#define NEAR_DRL    STB_AV1_NEAR_DRL
#define NEARISH_DRL STB_AV1_NEARISH_DRL

/* Compound inter types */
#define COMP_INTER_NONE           STB_AV1_COMP_INTER_NONE
#define COMP_INTER_WEIGHTED_AVG   STB_AV1_COMP_INTER_WEIGHTED_AVG
#define COMP_INTER_AVG            STB_AV1_COMP_INTER_AVG
#define COMP_INTER_SEG            STB_AV1_COMP_INTER_SEG
#define COMP_INTER_WEDGE          STB_AV1_COMP_INTER_WEDGE

/* Inter-intra types */
#define INTER_INTRA_NONE  STB_AV1_INTER_INTRA_NONE
#define INTER_INTRA_BLEND STB_AV1_INTER_INTRA_BLEND
#define INTER_INTRA_WEDGE STB_AV1_INTER_INTRA_WEDGE

/* Dav1dFilterMode -> our values */
#define DAV1D_N_FILTERS 4

#endif /* STB_AV1_LEVELS_COMPAT_H */

/* Additional intra prediction modes */
#define DIAG_DOWN_RIGHT_PRED STB_AV1_DIAG_DOWN_RIGHT_PRED
#define VERT_RIGHT_PRED      STB_AV1_VERT_RIGHT_PRED
#define HOR_DOWN_PRED        STB_AV1_HOR_DOWN_PRED
#define HOR_UP_PRED          STB_AV1_HOR_UP_PRED
#define VERT_LEFT_PRED       STB_AV1_VERT_LEFT_PRED
#define SMOOTH_V_PRED        STB_AV1_SMOOTH_V_PRED
#define SMOOTH_H_PRED        STB_AV1_SMOOTH_H_PRED

/* Additional filter 2D modes */
#define FILTER_2D_8TAP_REGULAR_SMOOTH  STB_AV1_FILTER_2D_8TAP_REGULAR_SMOOTH
#define FILTER_2D_8TAP_REGULAR_SHARP   STB_AV1_FILTER_2D_8TAP_REGULAR_SHARP
#define FILTER_2D_8TAP_SHARP_REGULAR   STB_AV1_FILTER_2D_8TAP_SHARP_REGULAR
#define FILTER_2D_8TAP_SHARP_SMOOTH    STB_AV1_FILTER_2D_8TAP_SHARP_SMOOTH
#define FILTER_2D_8TAP_SHARP           STB_AV1_FILTER_2D_8TAP_SHARP
#define FILTER_2D_8TAP_SMOOTH_REGULAR  STB_AV1_FILTER_2D_8TAP_SMOOTH_REGULAR
#define FILTER_2D_8TAP_SMOOTH          STB_AV1_FILTER_2D_8TAP_SMOOTH
#define FILTER_2D_8TAP_SMOOTH_SHARP    STB_AV1_FILTER_2D_8TAP_SMOOTH_SHARP

/* Dav1dFilterMode enums (inline values for compat) */
#define DAV1D_FILTER_8TAP_REGULAR 0
#define DAV1D_FILTER_8TAP_SHARP   1
#define DAV1D_FILTER_8TAP_SMOOTH  2
#define DAV1D_FILTER_BILINEAR     3

/* Additional intra prediction modes */
#define DIAG_DOWN_RIGHT_PRED STB_AV1_DIAG_DOWN_RIGHT_PRED
#define VERT_RIGHT_PRED      STB_AV1_VERT_RIGHT_PRED
#define HOR_DOWN_PRED        STB_AV1_HOR_DOWN_PRED
#define HOR_UP_PRED          STB_AV1_HOR_UP_PRED
#define VERT_LEFT_PRED       STB_AV1_VERT_LEFT_PRED
#define SMOOTH_V_PRED        STB_AV1_SMOOTH_V_PRED
#define SMOOTH_H_PRED        STB_AV1_SMOOTH_H_PRED

/* Additional filter 2D modes */
#define FILTER_2D_8TAP_REGULAR_SMOOTH  STB_AV1_FILTER_2D_8TAP_REGULAR_SMOOTH
#define FILTER_2D_8TAP_REGULAR_SHARP   STB_AV1_FILTER_2D_8TAP_REGULAR_SHARP
#define FILTER_2D_8TAP_SHARP_REGULAR   STB_AV1_FILTER_2D_8TAP_SHARP_REGULAR
#define FILTER_2D_8TAP_SHARP_SMOOTH    STB_AV1_FILTER_2D_8TAP_SHARP_SMOOTH
#define FILTER_2D_8TAP_SHARP           STB_AV1_FILTER_2D_8TAP_SHARP
#define FILTER_2D_8TAP_SMOOTH_REGULAR  STB_AV1_FILTER_2D_8TAP_SMOOTH_REGULAR
#define FILTER_2D_8TAP_SMOOTH          STB_AV1_FILTER_2D_8TAP_SMOOTH
#define FILTER_2D_8TAP_SMOOTH_SHARP    STB_AV1_FILTER_2D_8TAP_SMOOTH_SHARP

/* Dav1dFilterMode */
#define DAV1D_FILTER_8TAP_REGULAR 0
#define DAV1D_FILTER_8TAP_SHARP   1
#define DAV1D_FILTER_8TAP_SMOOTH  2
#define DAV1D_FILTER_BILINEAR     3

/* Dav1dWarpedMotionParams stub */
#define DAV1D_WM_TYPE_IDENTITY 0
